import { ImageResponse } from "next/og";

export const size = { width: 32, height: 32 };
export const contentType = "image/png";

// Favicon: "MA" initials in red — auto-generated by Next.js
export default function Icon() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          background: "#c0392b",
          fontFamily: "Georgia, serif",
          fontSize: 13,
          fontWeight: 700,
          color: "#f5f0e8",
          letterSpacing: "-0.5px",
        }}
      >
        MA
      </div>
    ),
    { ...size }
  );
}
